#!/bin/bash
# /etc/init.d/bootPostPic
SERVER='http://poachnetcs.mybluemix.net/uploader'

date=$(date +"%Y-%m-%d_%H-%M-%S")

raspistill -o "/home/pi/PoachNet/pics/$date.jpg"

	curl -i -X POST -F file=@/home/pi/PoachNet/pics/$date.jpg $SERVER
	#Send the picture off to the server

sleep 900
sudo shutdown -h now
